config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # root to: redirect('/users/sign_up')
  devise_for :users
  resources :comments
  root to: redirect('/posts')
  get 'pages/info'
  resources :posts do
    resources :likes
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: %i[signup login]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Sniff was sockcessful' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.post, notice: 'Sniff pupdated' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post_used = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_used, notice: 'Nothing to be sniffed at here' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:user_id, :body, :post_id)
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def info; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user != current_user
      redirect_to @post, alert: 'You can only edit your own barks'
    elsif exceed_time_limit
      redirect_to @post, alert: 'Edit time limit exceeded!'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Your bark was heard all around the Park!' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Bark was pawfectly pupdated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user != current_user
      redirect_to @post, alert: 'You can only chew your own posts'
    else
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Bark was chewed. Gone but not furgotten' }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:description, :picture)
  end

  def exceed_time_limit
    a = Time.now.to_s
    current_time = Time.parse(a)
    b = @post.created_at.to_s
    post_time = Time.parse(b)
    current_time - post_time > 600
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden">
    <%= form.label :body %>
  </div>

  <div class="field">
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <%= form.hidden_field :post_id %>
  <%= form.hidden_field :user_id %>
  <div class="actions">
    <%= form.submit "Sniff!" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Sniff</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Chew', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Posted by:</strong>
  <%= @comment.user.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post.description %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden">
    <%= form.label :description %>
  </div>

  <div class="field">
    <%= form.text_area :description %>
  </div>

  <div class="field">
    Add picture<br>
    <%= form.file_field :picture %><br><br>
  </div>

  <div class="hidden">
    <%= form.label :picture %>
  </div>

  <div class="actions">
    <%= form.submit "Bark!" %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Bark</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h1>🌳 Park 🌳</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <h2>Barks</h2>
    </div>
  </div>
  <% @posts.in_groups_of(1) do |group| %>
  <div class="row">
    <% group.compact.each do |post| %>
      <div class="col-md-6">
        <%= image_tag post.picture_url, width: '20%' if post.picture.present? %>
        <h5><%= simple_format link_to post.description, post %></h5>
        Posted by <%= post.user.name %> at
        <%= post.created_at.strftime("%k:%M, #{post.created_at.day.ordinalize} %B %Y") %>
        <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Lick' : 'Licks'%></p>
      </div>
    <% end %>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>New bark</h2>
  </div>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <h4>Bark 🔊</h4>
      <%= image_tag(@post.picture_url, width: '70%') if @post.picture.present? %>
      <p><strong><%= simple_format @post.description %></strong></p>
      Posted by <%= @post.user.name %> at
      <%= @post.created_at.strftime("%k:%M, #{@post.created_at.day.ordinalize} %B %Y") %>
      <p>
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Chew', @post, data: { confirm: 'Are you sure?' }, method: :delete %> |
        <%= link_to 'Back', posts_path %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1">
      <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
        <%= button_to 'Unlick', post_like_path(@post, pre_like), method: :delete %>
      <% else %>
        <%= button_to 'Lick', post_likes_path(@post), method: :post %>
      <% end %>
      <%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Lick' : 'Licks'%>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <h5>Sniffs</h5>
    </div>
  </div>

  <div class="row">
      <% @comments.each do |comment| %>
        <br>
        <div class="col-md-6">
        <p><%= comment.body %></p>

        Posted by <%= comment.user.name %> at
        <%= comment.created_at.strftime("%k:%M, #{comment.created_at.day.ordinalize} %B %Y") %>
          <p>
            <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
      <% end %>

  </div>

  <div class="row">
    <div class="col-md-5">
      <h5>New sniff:</h5>
      <%= render partial: 'comments/form', locals: { comment: @comment }, placeholder: "Write comment" %>
    </div>
  </div>
</div>